spring:
  data:
    mongodb:
      host: 192.168.0.38
      port: 27020
      username: root
      password: example
      database: chat_app_db
      authentication-database: admin

springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
